=== giosal/giosal.ge/ntic/book.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Le livre contient obligatoirement un book_title, un ou plusieurs authors, un ou plusieurs parties -->
<!ELEMENT book (book_title, author+, part+)> 	
<!-- lattribut lang est optionel -->
<!ATTLIST book 	lang CDATA #IMPLIED 
			year CDATA #REQUIRED
			discipline CDATA #REQUIRED>	
<!-- les element book_title et author sont de type PCDATA -->
<!ELEMENT book_title (#PCDATA)>
<!ELEMENT author (#PCDATA)>

<!--La partie contient ZERO ou UN titre et ZERO ou PLUSIEURS sections-->
<!ELEMENT part (part_title?, chapter*)>
<!-- l'attribut num_part de partie est de type CDATA et est obligatoire-->
<!ATTLIST part	num_part CDATA #REQUIRED> 
<!-- L'element part_title sont de type PCDATA -->
<!ELEMENT part_title (#PCDATA)>
<!--Le section contient ZERO ou UN titre, au moins un para-->
<!ELEMENT chapter (chapter_title?, para+)>
<!-- l'attribut num_chap de section est de type CDATA et est obligatoire-->
<!ATTLIST chapter num_chap CDATA #REQUIRED> 
<!-- l'element chapter_title est de type PCDATA-->
<!ELEMENT chapter_title (#PCDATA)>
<!-- l'element para est de type PCDATA-->
<!ELEMENT para (#PCDATA)>

=== giosal/giosal.ge/ntic/book.xml
<?xml version="1.0"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book>
    <book_title>
        MADAME BOVARY
    </book_title>
    <author>
        Gustave Flaubert
    </author>
    <part>
        <part_title>
            Première Partie
        </part_title>
        <chapter>
            <chapter_title>
                Chapitre I
            </chapter_title>
            <para>
                Nous étions à l’Étude, quand le Proviseur entra, suivi d’un nouveau habillé en bourgeois et d’un garçon de classe qui portait un grand pupitre. Ceux qui dormaient se réveillèrent, et chacun se leva comme surpris dans son travail.

                Le Proviseur nous fit signe de nous rasseoir; puis, se tournant vers le maître d’études:

                —-Monsieur Roger, lui dit-il à demi-voix, voici un élève que je vous recommande, il entre en cinquième. Si son travail et sa conduite sont méritoires, il passera dans les grands, où l’appelle son âge.

                Resté dans l’angle, derrière la porte, si bien qu’on l’apercevait à peine, le nouveau était un gars de la campagne, d’une quinzaine d’années environ, et plus haut de taille qu’aucun de nous tous. Il avait les cheveux coupés droit sur le front, comme un chantre de village, l’air raisonnable et fort embarrassé. Quoiqu’il ne fût pas large des épaules, son habit-veste de drap vert à boutons noirs devait le gêner aux entournures et laissait voir, par la fente des parements, des poignets rouges habitués à être nus. Ses jambes, en bas bleus, sortaient d’un. pantalon jaunâtre très tiré par les bretelles. Il était chaussé de souliers forts, mal cirés, garnis de clous.

                On commença la récitation des leçons. Il les écouta de toutes ses oreilles, attentif comme au sermon, n’osant même croiser les cuisses, ni s’appuyer sur le coude, et, à deux heures, quand la cloche sonna, le maître d’études fut obligé de l’avertir, pour qu’il se mît avec nous dans les rangs.
            </para>
        </chapter>
        <chapter>
            <chapter_title>
                Chapitre II
            </chapter_title>
            <para>
                Une nuit, vers onze heures, ils furent réveillés par le bruit d’un cheval qui s’arrêta juste à la porte. La bonne ouvrit la lucarne du grenier et parlementa quelque temps avec un homme resté en bas, dans la rue. Il venait chercher le médecin; il avait une lettre. Nastasie descendit les marches en grelottant, et alla ouvrir la serrure et les verrous, l’un après l’autre. L’homme laissa son cheval, et, suivant la bonne, entra tout à coup derrière elle. Il tira de dedans son bonnet de laine à houppes grises, une lettre enveloppée dans un chiffon, et la présenta délicatement à Charles, qui s’accouda sur l’oreiller pour la lire. Nastasie, près du lit, tenait la lumière. Madame, par pudeur, restait tournée vers la ruelle et montrait le dos.

                Cette lettre, cachetée d’un petit cachet de cire bleue, suppliait M. Bovary de se rendre immédiatement à la ferme des Bertaux, pour remettre une jambe cassée. Or il y a, de Tostes aux Bertaux, six bonnes lieues de traverse, en passant par Longueville et Saint- Victor. La nuit était noire. Madame Bovary jeune redoutait les accidents pour son mari. Donc il fut décidé que le valet d’écurie prendrait les devants. Charles partirait trois heures plus tard, au lever de la lune. On enverrait un gamin à sa rencontre, afin de lui montrer le chemin de la ferme et d’ouvrir les clôtures devant lui.
            </para>
        </chapter>
    </part>
    <part>
        <part_title>
            Deuxième Partie
        </part_title>
        <chapter>
            <chapter_title>
                Chapitre I
            </chapter_title>
            <para>
                Yonville-l’Abbaye (ainsi nommé à cause d’une ancienne abbaye de Capucins dont les ruines n’existent même plus) est un bourg à huit lieues de Rouen, entre la route d’Abbeville et celle de Beauvais, au fond d’une vallée qu’arrose la Rieule, petite rivière qui se jette dans l’Andelle, après avoir fait tourner trois moulins vers son embouchure, et où il y a quelques truites, que les garçons, le dimanche, s’amusent à pêcher à la ligne.

                On quitte la grande route à la Boissière et l’on continue à plat jusqu’au haut de la côte des Leux, d’où l’on découvre la vallée. La rivière qui la traverse en fait comme deux régions de physionomie distincte: tout ce qui est à gauche est en herbage, tout ce qui est à droite est en labour. La prairie s’allonge sous un bourrelet de collines basses pour se rattacher par derrière aux pâturages du pays de Bray, tandis que, du côté de l’est, la plaine, montant doucement, va s’élargissant et étale à perte de vue ses blondes pièces de blé. L’eau qui court au bord de l’herbe sépare d’une raie blanche la couleur des prés et celle des sillons, et la campagne ainsi ressemble à un grand manteau déplié qui a un collet de velours vert, bordé d’un galon d’argent.
            </para>
        </chapter>
        <chapter>
            <chapter_title>
                Chapitre II
            </chapter_title>
            <para>
                Emma descendit la première, puis Félicité, M. Lheureux, une nourrice, et l’on fut obligé de réveiller Charles dans son coin, où il s’était endormi complètement dès que la nuit était venue.

                Homais se présenta; il offrit ses hommages à Madame, ses civilités à Monsieur, dit qu’il était charmé d’avoir pu leur rendre quelque service, et ajouta d’un air cordial qu’il avait osé s’inviter lui- même, sa femme d’ailleurs étant absente.

                Madame Bovary, quand elle fut dans la cuisine, s’approcha de la cheminée. Du bout de ses deux doigts, elle prit sa robe à la hauteur du genou, et, l’ayant ainsi remontée jusqu’aux chevilles, elle tendit à la flamme, par-dessus le gigot qui tournait, son pied chaussé d’une bottine noire. Le feu l’éclairait en entier, pénétrant d’une lumière crue la trame de sa robe, les pores égaux de sa peau blanche et même les paupières de ses yeux qu’elle clignait de temps à autre. Une grande couleur rouge passait sur elle, selon le souffle du vent qui venait par la porte entrouverte.
            </para>
        </chapter>
    </part>
</book>
